version: '3'

services:

  backend:
    build: ./backend
    ports:
      - "1880:1880"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    
  frontend:
    build: ./frontend
    ports:
      - "8090:80"