version: '3'

services:

  backend:
    build: ./backend
    environment:
      FLOWS: /data/flows.json
      NODE_PATH: /usr/src/node-red/node_modules:/data/node_modules
    #restart: on-failure:5
    ports:
      - "1880:1880"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    
  frontend:
    build: ./frontend
    ports:
      - "80:80"