version: '3'

services:

  backend:
    image: chewett/hue-backend
    ports:
      - "1880:1880"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    
  frontend:
    image: chewett/hue-frontend
    ports:
      - "80:80"